name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '*/120 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1

      - name: Update contributions
        run: |
          npm i --prefix contrib
          npm run build --prefix contrib ${{ secrets.GRAPHQL_KEY }}

          git config --global user.name 'Safin Singh'
          git config --global user.email 'safin.singh@gmail.com'

          git commit -am "Update contributions"
          git push
